fix: don't pass locations until necessary
$ tsc && vite build
src/main.tsx:15:46 - error TS2322: Type '{ locations: Locations; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'locations' does not exist on type 'IntrinsicAttributes'.

15           <Route path="/" element={<HomePage locations={locations} />} />